---
- name: Test the oxide_ssh_key module
  hosts: localhost
  vars:
    key_name: "rusty-ansible-key"
  vars_files:
    - ./oxide_vault.yml
  module_defaults:
    oxide_ssh_key:
      oxide_host: "{{ oxide_api }}"
      oxide_token: "{{ oxide_token }}"
    oxide_ssh_key_info:
      oxide_host: "{{ oxide_api }}"
      oxide_token: "{{ oxide_token }}"
  tasks:
  tasks:

    - name: Fetch keys
      block:

        - name: Fetch all SSH keys
          oxide_ssh_key_info:
          register: all_keys

        - name: Display all SSH keys
          debug:
            var: all_keys.ssh_keys

        - name: Fetch specific SSH key by name
          oxide_ssh_key_info:
            name: "{{ key_name }}"
          register: specific_key

        - name: Display specific SSH key details
          debug:
            var: specific_key.ssh_key.public_key

    - name: Manage keys
      block:

        - name: Create SSH key
          oxide_ssh_key:
            name: "{{ key_name }}"
            public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
            description: "Created by Ansible"
            state: present

        - name: Idempodency check
          oxide_ssh_key:
            name: "{{ key_name }}"
            public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
            description: "Created by Ansible"
            state: present

        - name: Pause
          pause:
            seconds: 10

        - name: Delete SSH key
          oxide_ssh_key:
            name: "{{ key_name }}"
            state: absent

        - name: Delete SSH key check
          oxide_ssh_key:
            name: "{{ key_name }}"
            state: absent

        - name: Create SSH key
          oxide_ssh_key:
            name: "{{ key_name }}"
            public_key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
            state: present

    - name: Expected failures
      ignore_errors: true
      block:

        - name: Expected failure - Attempt to update a key (API will introduce this feature in the future)
          oxide_ssh_key:
            name: "{{ key_name }}"
            public_key: "different key"
            state: present

        - name: Expected failure - bad name
          oxide_ssh_key:
            name: "{{ item }}"
            public_key: "different key"
            state: present
          loop:
            - "Bad-Key-Name"
            - "-bad"
            - "bad-"
            - "longbad-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
